#!/bin/bash

if [[ -z $hdf5_therock_version ]]; then
        echo "Error: HDF5 version name has not been set."
        exit 1
fi

if [[ -z $mpich_therock_version ]]; then
        echo "Error: MPICH version name has not been set, needed to create the hdf5-parallel module."
        exit 1
fi

INSTALL_DIR="${BASE_PREFIX}/hdf5-parallel/${hdf5_therock_version}-${version_name}"
mkdir -p ${INSTALL_DIR}
if [[ $? -ne 0 ]]; then
        echo "Error: Failed to create directory '${INSTALL_DIR}'."
        exit 1
fi
mkdir -p $TMPDIR/tmp.hdf5 && cd $TMPDIR/tmp.hdf5
tar -xf $CACHE_DIR/$HDF5_RELEASE
if [[ $? -ne 0 ]]; then
        echo "Error: Failed to extract '$HDF5_RELEASE'."
        exit 1
fi
cd $TMPDIR/tmp.hdf5/${hdf5_release_dir}
if [[ $? -ne 0 ]]; then
        echo "Error: Failed to change directory to '${TMPDIR}/tmp.hdf5/${hdf5_release_dir}'."
        exit 1
fi


CONFIG_OPTIONS=" --enable-fortran --prefix=${INSTALL_DIR} --libdir=${INSTALL_DIR}/lib --enable-shared --disable-static --enable-optimization=high --disable-tests --enable-parallel "
CC=$(which mpicc) FC=$(which mpifort) CXX=$(which mpicxx) F77=$(which mpif77) ./configure ${CONFIG_OPTIONS}
if [[ $? -ne 0 ]]; then
        echo "Error: HDF5 configure failed."
        exit 1
fi

# Workaround for libtool bug with amdflang/amdclang drivers (same issue as in
# build.mpich-3.4a2.sh): configure leaves wl="" and pic_flag="" empty for the
# AMD compiler tags, so libtool passes raw linker flags (--whole-archive,
# -soname, ...) directly to the compiler driver, which fails with:
#   flang-23: error: unknown argument: '--whole-archive'
# Rewriting wl="" -> wl="-Wl," makes libtool prefix linker flags with -Wl,
# which the AMD drivers forward to the linker.
# Also patch all sub-libtools generated by HDF5's recursive configure.
# Ref: https://github.com/HDFGroup/hdf5/issues/366
find . -type f -name libtool -print0 | xargs -0 sed -i \
    -e 's/wl=""/wl="-Wl,"/g' \
    -e 's/pic_flag=""/pic_flag=" -fPIC -DPIC"/g'

make -j12
if [[ $? -ne 0 ]]; then
        echo "Error: HDF5 build failed."
        exit 1
fi
make install
if [[ $? -ne 0 ]]; then
        echo "Error: HDF5 install failed."
        exit 1
fi

MODULE_DIR="${BASE_PREFIX}/modulefiles/${release_name}/hdf5-parallel"
mkdir -p ${MODULE_DIR}
MODULE_FILE="${MODULE_DIR}/${hdf5_therock_version}.lua"
echo "whatis(\"Name: hdf5\")"                                            > $MODULE_FILE
echo "whatis(\"Version: ${hdf5_therock_version}\")"                      >> $MODULE_FILE
echo "whatis(\"Category: library\")"                                     >> $MODULE_FILE
echo "whatis(\"Description: High-performance data management and storage suite\")"  >> $MODULE_FILE
echo "whatis(\"URL: https://www.hdfgroup.org/solutions/hdf5/\")"         >> $MODULE_FILE
echo ""                                                                  >> $MODULE_FILE
echo "local base = \"${INSTALL_DIR}\""                                   >> $MODULE_FILE
echo ""                                                                  >> $MODULE_FILE
echo "depends_on(\"mpich/${mpich_therock_version}\")"                    >> $MODULE_FILE
echo ""                                                                  >> $MODULE_FILE
echo "prepend_path(\"LD_LIBRARY_PATH\", pathJoin(base, \"lib\"))"        >> $MODULE_FILE
echo "prepend_path(\"LIBRARY_PATH\", pathJoin(base, \"lib\"))"           >> $MODULE_FILE
echo "prepend_path(\"C_INCLUDE_PATH\", pathJoin(base, \"include\"))"     >> $MODULE_FILE
echo "prepend_path(\"CPLUS_INCLUDE_PATH\", pathJoin(base, \"include\"))" >> $MODULE_FILE
echo "prepend_path(\"CPATH\", pathJoin(base, \"include\"))"              >> $MODULE_FILE
echo "prepend_path(\"INCLUDE\", pathJoin(base, \"include\"))"            >> $MODULE_FILE
echo "prepend_path(\"PATH\", pathJoin(base, \"bin\"))"                   >> $MODULE_FILE
echo "setenv(\"HDF5_DIR\",base)"                                         >> $MODULE_FILE
echo "setenv(\"HDF5_ROOT\",base)"                                        >> $MODULE_FILE

#cd ${TMPDIR} && rm -rf ${TMPDIR}/tmp.hdf5



